In [1]:
import pandas as pd

from csgo_wp import data_transform

In [2]:
df = pd.read_csv('G:/datasets/csgo/example_frames.csv', nrows=10000)

In [7]:
df.shape

(5000, 24)

In [5]:
df[['MatchId', 'MapName']].drop_duplicates().values.tolist()

[[3, 'de_inferno']]

In [6]:
transformed_df = data_transform.transform_data(df, 'de_inferno')

g:\git\csgo-win-probability\csgo_wp\data_transform.py:52: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pos'] = df[['X', 'Y', 'Z']].values.tolist()


In [7]:
import torch

n_samples = transformed_df[0].shape[0]
stacked = torch.cat([x.reshape(n_samples, -1) for x in transformed_df], dim=1).view(n_samples, 10, 12)

RuntimeError: shape '[10, 10, 12]' is invalid for input of size 60000

In [ ]:
stacked[:, :, :10].shape

In [8]:
transformed_df.shape

torch.Size([500, 10, 12])

In [9]:
df.columns

Index(['MatchId', 'MapName', 'RoundNum', 'Tick', 'Seconds', 'BombPlanted',
       'BombSite', 'PlayerId', 'SteamId', 'TeamId', 'Side', 'X', 'Y', 'Z',
       'XViz', 'YViz', 'AreaId', 'EqVal', 'Hp', 'Armor', 'HasDefuse',
       'HasHelmet', 'Created', 'Updated'],
      dtype='object')

In [19]:
pd.options.display.max_columns = 999
df.head()

MatchId     MapName  RoundNum   Tick  Seconds  BombPlanted  BombSite  \
0        3  de_inferno         1  15926       20            1       NaN   
1        3  de_inferno         1  15926       20            1       NaN   
2        3  de_inferno         1  15926       20            1       NaN   
3        3  de_inferno         1  15926       20            1       NaN   
4        3  de_inferno         1  15926       20            1       NaN   

   PlayerId            SteamId  TeamId Side            X            Y  \
0        16  76561197961610974       5   CT  2315.194092  2039.947144   
1        18  76561198017671061       5   CT  2381.296387  2050.294434   
2        21  76561197962710908       5   CT  2460.788818  2027.771484   
3        23  76561198027839825       5   CT  2426.017090  1946.936890   
4        25  76561198013172503       5   CT  2296.003174  1958.576782   

           Z  XViz  YViz  AreaId  EqVal   Hp  Armor  HasDefuse  HasHelmet  \
0  128.03125   NaN   NaN      67    850  100    100          1          1   
1  128.03125   NaN   NaN      68    900  100      0          1          1   
2  132.03125   NaN   NaN      68    900  100      0          1          1   
3  128.03125   NaN   NaN      91    850  100    100          1          1   
4  128.03125   NaN   NaN      67    850  100    100          1          1   

               Created              Updated  
0  2020-07-24 23:43:26  2020-07-24 23:43:26  
1  2020-07-24 23:43:26  2020-07-24 23:43:26  
2  2020-07-24 23:43:26  2020-07-24 23:43:26  
3  2020-07-24 23:43:26  2020-07-24 23:43:26  
4  2020-07-24 23:43:26  2020-07-24 23:43:26

In [11]:
df['Tick'].nunique()

500

In [11]:
player_id_check = pd.read_csv('G:/datasets/csgo/example_frames.csv', usecols=['PlayerId', 'SteamId'])

In [12]:
player_id_check.head()

PlayerId            SteamId
0        16  76561197961610974
1        18  76561198017671061
2        21  76561197962710908
3        23  76561198027839825
4        25  76561198013172503

In [13]:
player_id_check.shape

(7840516, 2)

In [14]:
grouped = player_id_check.groupby('PlayerId').agg({'SteamId': 'nunique'})

In [15]:
grouped.head()

SteamId
PlayerId         
1               1
3               2
4               2
16              1
17              1

In [17]:
player_id_check[player_id_check['PlayerId'] == 3]['SteamId'].unique()

array([76561198113666193, 76561198017671061], dtype=int64)

In [44]:
torch.rand(1).item()

0.8759033679962158

In [9]:
match_map_check = pd.read_csv('G:/datasets/csgo/example_frames.csv', usecols=['MatchId', 'MapName', 'RoundNum'])

In [10]:
match_map_check.drop_duplicates().shape

(1295, 3)

In [9]:
df['MapName'].unique()[0]

'de_inferno'

In [2]:
from csgo_wp.data_transform import CSGODataset

In [3]:
dataset = CSGODataset(transform=data_transform.transform_data)

Calculating sample index offsets...
Done!


In [4]:
len(dataset)

508444

In [7]:
tick_count_check = pd.read_csv('G:/datasets/csgo/example_frames.csv', usecols=['MatchId', 'MapName', 'RoundNum', 'Tick'])

In [10]:
tick_count_check.drop_duplicates().shape

(844207, 4)

In [12]:
508444/844207

0.6022740868057241

In [15]:
len(CSGODataset(transform=data_transform.transform_data, dataset_split='val')) / 1, len(CSGODataset(transform=data_transform.transform_data, dataset_split='test')) / 1

Calculating sample index offsets...
Done!
Calculating sample index offsets...
Done!


(168060.0, 167703.0)

In [24]:
df['MatchId'].values[0]

3

In [5]:
dataset[10000]

g:\git\csgo-win-probability\csgo_wp\data_transform.py:53: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pos'] = df[['X', 'Y', 'Z']].values.tolist()


113 de_inferno 6


(tensor([[ 1., 10.,  7., 11., 12., 43., 38., 12., 34., 10.],
         [10.,  1., 18.,  4.,  3., 34., 35.,  3., 30.,  3.],
         [ 7., 18.,  1., 19., 20., 44., 37., 20., 33., 18.],
         [11.,  4., 19.,  1.,  6., 37., 38.,  6., 33.,  2.],
         [12.,  3., 20.,  6.,  1., 32., 33.,  1., 28.,  5.],
         [43., 34., 44., 37., 32.,  1., 10., 32., 12., 36.],
         [38., 35., 37., 38., 33., 10.,  1., 33.,  6., 37.],
         [12.,  3., 20.,  6.,  1., 32., 33.,  1., 28.,  5.],
         [34., 30., 33., 33., 28., 12.,  6., 28.,  1., 32.],
         [10.,  3., 18.,  2.,  5., 36., 37.,  5., 32.,  1.],
         [ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.],
         [ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.]]), tensor([[1.]]))

In [8]:
dataset[10000][0].shape

g:\git\csgo-win-probability\csgo_wp\data_transform.py:53: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pos'] = df[['X', 'Y', 'Z']].values.tolist()


113 de_inferno 6


torch.Size([10, 12])

In [11]:
data_transform.transform_data(pd.read_csv('G:/datasets/csgo/match-map-unique/train/match-113-de_inferno-6-676.csv'), 'de_inferno')[0]

g:\git\csgo-win-probability\csgo_wp\data_transform.py:53: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pos'] = df[['X', 'Y', 'Z']].values.tolist()


tensor([[ 1., 52.,  2., 55., 52.,  3.,  2., 49.,  1., 53., 52.,  1.],
        [53.,  4.,  1., 50., 51.,  2., 52.,  2.,  2., 53.,  1., 56.],
        [53.,  4.,  3., 50.,  2., 54., 55.,  4., 56.,  1.,  4., 53.],
        [54.,  5., 55.,  3., 52.,  1., 53.,  4.,  1., 50., 51.,  2.],
        [52.,  2.,  3., 50.,  4., 53., 50.,  1.,  2., 47.,  3., 51.],
        [ 2., 51.,  3., 54., 51.,  2.,  1., 48.,  2., 52., 49.,  2.],
        [50.,  5.,  2., 47., 48.,  1., 49.,  3.,  1., 52.,  2., 55.],
        [52.,  3.,  2., 49.,  1., 53., 53.,  2., 54.,  3.,  2., 51.],
        [52.,  3., 53.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
        [ 1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.]])

In [3]:
import torch
import time
from csgo_wp.data_transform import CSGODataset, transform_data
import warnings
warnings.filterwarnings('ignore')

dataset = CSGODataset(transform=transform_data)

loader = torch.utils.data.DataLoader(dataset,
                                         batch_size=2,
                                         shuffle=True,
                                         num_workers=0,
                                         )
start = time.time()
# check if dataset acts as expected
for index, (data, target) in enumerate(loader):
    print(index, data.shape, target.shape)
    break
print(time.time() - start)

Calculating sample index offsets...
Done!
(4800, 9) (38400, 19) 600
(4800, 8)
(6192, 9) (55728, 19) 688
(6192, 9)


RuntimeError: stack expects each tensor to be equal size, but got [10, 8] at entry 0 and [11, 9] at entry 1

In [3]:
%timeit dataset[10000]

Calculating sample index offsets...
Done!
5.33 s ± 191 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
import pandas as pd
row_count_check = pd.read_csv('G:/datasets/csgo/match-map-unique/train/match-58-de_inferno-17-687.csv')

In [5]:
row_count_check

Unnamed: 0  MatchId     MapName  RoundNum    Tick  Seconds  BombPlanted  \
0        1294817       58  de_inferno        17  243484       15            1   
1        1294818       58  de_inferno        17  243484       15            1   
2        1294819       58  de_inferno        17  243484       15            1   
3        1294820       58  de_inferno        17  243484       15            1   
4        1294821       58  de_inferno        17  243484       15            1   
...          ...      ...         ...       ...     ...      ...          ...   
5491     1300308       58  de_inferno        17  259975      144            1   
5492     1300309       58  de_inferno        17  259975      144            1   
5493     1300310       58  de_inferno        17  259975      144            1   
5494     1300311       58  de_inferno        17  259975      144            1   
5495     1300312       58  de_inferno        17  259975      144            1   

     BombSite  PlayerId            SteamId  ...  XViz YViz  AreaId  EqVal  \
0         NaN       317  76561198068168375  ...   NaN  NaN      68   2000   
1         NaN       318  76561198040378969  ...   NaN  NaN     227   1850   
2         NaN       321  76561197982495276  ...   NaN  NaN      68   2300   
3         NaN       322  76561198142085482  ...   NaN  NaN      67   2050   
4         NaN       312  76561198042147080  ...   NaN  NaN    1060   3600   
...       ...       ...                ...  ...   ...  ...     ...    ...   
5491        B       322  76561198142085482  ...   NaN  NaN     219   2050   
5492        B       312  76561198042147080  ...   NaN  NaN     287   3600   
5493        B       314  76561197990650065  ...   NaN  NaN     287   3900   
5494        B       315  76561198056070039  ...   NaN  NaN     287   4600   
5495        B       316  76561198202581684  ...   NaN  NaN     287   3350   

       Hp  Armor  HasDefuse  HasHelmet              Created  \
0     100    100          1          1  2020-07-25 00:54:52   
1     100    100          1          1  2020-07-25 00:54:52   
2     100    100          1          1  2020-07-25 00:54:52   
3     100    100          1          1  2020-07-25 00:54:52   
4     100    100          1          1  2020-07-25 00:54:52   
...   ...    ...        ...        ...                  ...   
5491    0      0          1          1  2020-07-25 00:54:52   
5492    0      0          1          1  2020-07-25 00:54:52   
5493    0      0          1          1  2020-07-25 00:54:52   
5494    0      0          1          1  2020-07-25 00:54:52   
5495    0      0          1          1  2020-07-25 00:54:52   

                  Updated  
0     2020-07-25 00:54:52  
1     2020-07-25 00:54:52  
2     2020-07-25 00:54:52  
3     2020-07-25 00:54:52  
4     2020-07-25 00:54:52  
...                   ...  
5491  2020-07-25 00:54:52  
5492  2020-07-25 00:54:52  
5493  2020-07-25 00:54:52  
5494  2020-07-25 00:54:52  
5495  2020-07-25 00:54:52  

[5496 rows x 25 columns]

In [8]:
print(row_count_check['Tick'].min(), row_count_check['Tick'].max())
grouped = row_count_check.groupby('Tick').agg({'MatchId': 'count'})
grouped[grouped['MatchId'] != 10]

243484 259975


MatchId
Tick           
243484        8
243488        8
243524        8
243560        8
243564        8
...         ...
259830        8
259878        8
259918        8
259962        8
259975        8

[687 rows x 1 columns]

In [12]:
row_count_check['SteamId'].nunique()

8

In [14]:
8 ** 2

64